services:
  blogapp:
    container_name: blogapp
    build:
      context: ./BlogApp   
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - API_URL=${API_URL}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
networks:
  default:
      external: true
      name: blog-network

