services:
  blogapp:
    container_name: blogapp
    build:
      context: ./BlogApp   
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://blogapi:8080
      - ASPNETCORE_ENVIRONMENT=Development
networks:
  default:
      external: true
      name: blog-network

