services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  blogapi:
    container_name: blogapi
    build:
      context: ./BlogAPI
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
networks:
  default:
      external: true
      name: blog-network